spring.application.name=fintrack-backend

#DB Address
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

#DB Username By Default - postgres
spring.datasource.username=postgres

#Db PassWord = root set on the time of installation
spring.datasource.password=root

#control for auto commit
spring.jpa.hibernate.ddl-auto=update

# Enable SQL logging to the console
spring.jpa.show-sql=true

# Pretty-print/Format the SQL statements for readability
spring.jpa.properties.hibernate.format_sql=true

# xml support
#spring.mvc.contentnegotiation.favor-parameter=true
