spring.application.name=fintrack-backend

#DB Address
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

#DB Username By Default - postgres
spring.datasource.username=postgres

#Db PassWord = root set on the time of installation
spring.datasource.password=root

#control for auto commit
spring.jpa.hibernate.ddl-auto=update
